parameter_defaults:

  ControllerCount: 3 
  OvercloudControllerFlavor: control 

  ComputeCount: 2 
  OvercloudComputeFlavor: compute 

  CephStorageCount: 3
  OvercloudCephStorageFlavor: ceph-storage

  NtpServer: '206.108.0.134'
  NeutronNetworkType: 'vxlan,vlan' 
  NeutronTunnelTypes: 'vxlan' 

  # additional settings

  NovaReservedHostMemory: 1024 
  DockerPuppetProcessCount: 1 

